### ISSUE TITLE
Passing SQL Query to DB middleware

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#83] opened 2022-02-01 11:38 UTC
Two statements in the DB-mw like: 

```
Given I have a database uri named 'myDb1'
Given I have a database table named 'myTable'
Given I execute the query 'myQuery1' on the database 'myDb1' and save the result into 'myZenroomStringDictionary'
Given I have a 'string dictionary' named 'myZenroomStringDictionary'
When I create the random object of '128' bits
Then I execute the query 'myQuery2' on the database 'myDb1' with the data 'random_object'

```
Queries (they are randomly selected sample queries):

```
myQuery1: 
  SELECT *
  FROM call
  ORDER BY
      call.employee_id ASC,
      call.start_time ASC;

myQuery2: 
  SELECT *
  FROM call
  ORDER BY
      call.employee_id ASC,
      call.start_time ASC;
```

**Comment by puria** [comment] 2022-02-01 15:19
Duplicate of https://github.com/dyne/restroom-mw/issues/51

**Comment by puria** [comment] 2022-02-01 15:22
Rememeber that in JSON we don't have the newlines to the query would be in form of
```
{
  myQuery: "SELECT *\n  FROM call\n ORDER BY\n      call.employee_id ASC,\n      call.start_time ASC;\n"
}
```

**Closed** 2022-05-17 07:45 UTC
Labels: enhancement
